// Builds the installed Meme Lab app for Cloudflare into app/dist/.
//   Runs from `npx wrangler deploy` (the build command in wrangler.jsonc), or by hand: npm run build:app
// The page is the Apps Script page (apps-script/Index.html with its parts filled in) plus
// app/engine.js, which answers google.script.run by calling the engine (apps-script/Api.gs).
import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";

const root = new URL("../", import.meta.url).pathname;
const read = (p) => readFileSync(root + p, "utf8");
const dist = root + "app/dist/";

rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });
cpSync(root + "app/public", dist, { recursive: true });

const head = `<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>Meme Lab</title>
<meta name="theme-color" content="#1E6B46">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="Meme Lab">
<link rel="manifest" href="manifest.webmanifest">
<link rel="icon" href="icon-192.png">
<link rel="apple-touch-icon" href="apple-touch-icon.png">`;

let html = read("apps-script/Index.html")
  .replace(/<!-- Generated by[^>]*-->\n/, "<!-- Built by scripts/build-app.mjs from apps-script/Index.html and app/engine.js. -->\n")
  .replace('<base target="_top">', head)
  .replace("<?!= include('DbClient'); ?>", `<script>\n${read("app/engine.js")}</script>\n<?!= include('DbClient'); ?>`)
  .replace(/<\?!= include\('(\w+)'\); \?>/g, (_, name) => read(`apps-script/${name}.html`));
if (html.includes("<?")) throw new Error("apps-script/Index.html has a template tag the build doesn't know");
writeFileSync(dist + "index.html", html);

let version = process.env.WORKERS_CI_COMMIT_SHA || process.env.CF_PAGES_COMMIT_SHA || "";
if (!version) try { version = execSync("git rev-parse --short HEAD", { cwd: root }).toString().trim(); } catch (e) { version = String(Date.now()); }
writeFileSync(dist + "sw.js", read("app/public/sw.js").replace("__VERSION__", version.slice(0, 12)));
console.log(`Built app/dist/ (version ${version.slice(0, 12)})`);
